[package]
name = "string_processor"
version = "0.2.0"
edition = "2024"
description = "String Template Processor"
license = "MIT"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.39", features = ["derive"] }
