[package]
name = "string_processor"
version = "0.1.0"
edition = "2024"
description = "POC for television template parser"
license = "MIT"

[dependencies]
regex = "1.11.1"
clap = { version = "4.5.39", features = ["derive"] }
